### ISSUE TITLE
Fix CSS/Bootstrap issue in all views.

### ISSUE THREAD

**Issue by YogenRaii** [miyoz/gurufinder#217]
- Right now the footer is not being shown at bottom rather white space as in picture is being shown. Footer must be there instead of white space.

![right-now](https://user-images.githubusercontent.com/14182415/28854812-df5f7baa-76fe-11e7-8c2c-1267d204a163.jpg)

- find the required one
![required](https://user-images.githubusercontent.com/14182415/28854859-0b65d65e-76ff-11e7-90a5-582c9d0268d8.jpg)

**Comment by binaydesar** [comment]
@YogenRaii - Actually this is the design for the template putting a footer below the screen. But yeah it's somehow looking weird with those white spaces. So I think we should discuss on this one. It would also be better putting those forms little below at the center.

**Comment by YogenRaii** [comment]
@binaydesar i agree... so if not @Bassem3007 somebody has to work on this...
