### ISSUE TITLE
Ng2Completer module can not be found in app.module.ts.

### ISSUE THREAD

**Issue by miyoz** [miyoz/gurufinder#223]
- may be version or installation is not correct. Plz fix this.

**Comment by githubniraj** [comment]
I did see the module, I just spotted the module on the app.module.ts file, 

![image](https://user-images.githubusercontent.com/12106299/28883931-b68e0274-7775-11e7-9ed0-1af8cdbf38ae.png)

**Comment by miyoz** [comment]
pfa

![ng2completer](https://user-images.githubusercontent.com/30029985/28884652-5c67924e-7778-11e7-8116-04b559c83870.jpg)

Even though app is working once we do `npm install`, it is still showing this.

**Comment by githubniraj** [comment]
npm install should work, give a try npm prune and npm install again

**Comment by miyoz** [comment]
looks good... is there any we can update script to do it automatically? If you have let me know... else you can close this issue marking duplicate!!

**Comment by githubniraj** [comment]
i think we can write script and let it run while running npm start, and also before pushing we can run ng lint so that we can get rid of getting errors on the travis. I will so some research and update about it.
