### ISSUE TITLE
Create methods on service and component, if required, to pull the student info.

### ISSUE THREAD

**Issue by YogenRaii** [miyoz/gurufinder#242]
- you have to work in registered-user module

**Comment by shyamuneupane** [comment]
is it on front end or back end ?

**Comment by YogenRaii** [comment]
@shyamuneupane if you look into reg-user info in `/user` , it is hardcoded... but it should have been from the server... so once login is successful, you have call GET endpoint ... `/auth/me` to pull up your info and store into localStorage and display there
